name: Deliver Tokens To Consumer

on:
  workflow_dispatch:
  push:
    paths:
      - "11-design-tokens/output/**"

jobs:
  deliver_to_react_application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-design-tokens
    steps:
      - uses: actions/checkout@v2
      - name: Deliver Platform Deliverable To Application
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: "11-design-tokens/output/js"
          destination-username: "solygambas"
          destination-repository: "react-projects"
          destination-directory: "playground/03-tokens"
          commit-email: ${{ secrets.API_GITHUB_COMMIT_EMAIL }}
