name: Deliver Tokens To Consumer

on:
  workflow_dispatch:
  push:
    paths:
      - "11-design-tokens/output/**"

jobs:
  deliver_to_react_application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-design-tokens
    steps:
      - uses: actions/checkout@v2
      - name: Deliver Platform Deliverable To Application
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 11-design-tokens/output/js
          destination-github-username: "solygambas"
          destination-repository-name: "react-projects"
          user-email: ${{ secrets.API_GITHUB_COMMIT_EMAIL }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
          target-directory: "playground/03-tokens/tokens"
