name: Generate Tokens on Input

on:
  push:
    paths:
      - "11-design-tokens/input/design-tokens.tokens.json"

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 11-design-tokens
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update platform deliverables
